### ISSUE TITLE
BMS File is not created

### ISSUE THREAD

**Issue by SixBeeps** [mashimycota/om2bms#1] opened 2019-08-29 10:24 UTC
Upon processing a beatmap, the program seems to generate the BMS file, but it doesn't get saved. My directory output *is* set.

**Comment by mashimycota** [comment] 2019-09-09 16:38
I'm having trouble reproducing this. Please do comment specifically which maps you are trying to convert.
Are you using `om2bms.py` or `om2bms_osz.py`?

Keep in mind this ignores all non-7k/8k mania maps; the maps being converted should be printed to console as:

> `        Converting [song_name] [difficulty_name].osu`

**Comment by SixBeeps** [comment] 2019-09-09 21:59
Using `om2bms.py`, I convert an 8k .osu file, and I get the following output:

> Converting C:\Users\brand\Desktop\hold.osu
> Done

However, the file doesn't appear in the path I put in the `default_outdir.ini` file. The folder specified does exist, but there are no output files.
![Capture](https://user-images.githubusercontent.com/19637928/64569463-8fbb9300-d32b-11e9-8053-4b83725bc8c0.PNG)

**Comment by mashimycota** [comment] 2019-09-10 04:54
`om2bms.py` outputs the BMS files into the same directory as `om2bms.py`. `default_outdir.ini` is only used for `om2bms_osz.py`. I recommend using `om2bms_osz.py` as it does all the work of transferring the files for you.

If the problem persists I think it may be a permission error. Try moving the .py files onto the same drive as the .osu file and running cmd as adminstrator.

**Comment by SixBeeps** [comment] 2019-09-10 10:27
I would much prefer to just process the .osu individually (a.k.a. I don't know how to Python and use pip) so using `om2bms_osz.py` isn't much of an option :\

I tried running `om2bms.py` with the beatmap in the same folder and with cmd elevated, but there's still nothing being output.

**Comment by mashimycota** [comment] 2019-09-10 16:17
To check what version of Python you are running run:
> `python --version`

I have not tested it anything below Python 3.6 so please update your Python if it is <3.6.
To install the only dependency run:

> `python -m pip install Pillow`

Now you should be able to run `om2bms_osz.py`.


If you are not, try converting a ranked map and see if it has the same problem. There may be some incorrect/missing metadata in the .osu files you are trying to convert. If the problem is in the maps you are trying to convert, please link it if you are able to.

**Closed as completed** 2019-10-18 05:44 UTC
